apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: javase
    app_name: request-timer
    template: javase
  name: request-timer
spec:
  replicas: 40
  selector:
    app_name: request-timer
    deploymentconfig: request-timer
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app_name: request-timer
        deploymentconfig: request-timer
        template: javase
    spec:
      containers:
      - env:
        - name: APP_NAME
          value: request-timer
        - name: ARTIFACT_URL
          value: https://git.global.paas.gsnetcloud.corp/apps/request-timer/raw/master/target/request-timer-0.0.1-SNAPSHOT.jar
        - name: PBD_URL
        - name: JAVA_OPTS_EXT
          value: -Djava.security.egd=file:/dev/./urandom
        - name: JAVA_PARAMETERS
        - name: PROJECT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: WILY_MOM_FQDN
        - name: WILY_MOM_PORT
          value: "5001"
        - name: TZ
          value: Europe/Madrid
        image: registry.boae.paas.gsnetcloud.corp/produban/javase
        imagePullPolicy: IfNotPresent
        name: request-timer
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 512M
          requests:
            memory: 512M
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/metadata
          name: podinfo
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: podinfo
  test: false
  triggers:
  - type: ConfigChange
status: {}