apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2018-07-25T08:25:30Z
  generation: 21
  labels:
    app: javase
    app_name: request-timer
    template: javase
  name: request-timer
  namespace: load-testing
  resourceVersion: "14541628"
  selfLink: /apis/apps.openshift.io/v1/namespaces/load-testing/deploymentconfigs/request-timer
  uid: 4b0bc951-8fe4-11e8-a29a-005056a07122
spec:
  replicas: 40
  selector:
    app_name: request-timer
    deploymentconfig: request-timer
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app_name: request-timer
        deploymentconfig: request-timer
        template: javase
    spec:
      containers:
      - env:
        - name: APP_NAME
          value: request-timer
        - name: ARTIFACT_URL
          value: https://git.global.paas.gsnetcloud.corp/apps/request-timer/raw/master/target/request-timer-0.0.1-SNAPSHOT.jar
        - name: PBD_URL
        - name: JAVA_OPTS_EXT
          value: -Djava.security.egd=file:/dev/./urandom
        - name: JAVA_PARAMETERS
        - name: PROJECT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: WILY_MOM_FQDN
        - name: WILY_MOM_PORT
          value: "5001"
        - name: TZ
          value: Europe/Madrid
        image: registry.boae.paas.gsnetcloud.corp/produban/javase
        imagePullPolicy: IfNotPresent
        name: request-timer
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 512M
          requests:
            memory: 512M
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/metadata
          name: podinfo
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: podinfo
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 40
  conditions:
  - lastTransitionTime: 2018-07-25T08:33:06Z
    lastUpdateTime: 2018-07-25T08:33:13Z
    message: replication controller "request-timer-2" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2018-08-16T10:20:41Z
    lastUpdateTime: 2018-08-16T10:20:41Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 2
  observedGeneration: 21
  readyReplicas: 40
  replicas: 40
  unavailableReplicas: 0
  updatedReplicas: 40
